'use client';
import { useMemo, useState } from 'react';
import { useWebMCP, type WebMCPTool } from './useWebMCP';
import { usePersistentState } from './usePersistentState';
const projects=[
{id:'orchard',title:'Revive the schoolyard orchard',area:'North End',type:'Outdoors',time:2,people:8,color:'lime',keywords:'garden gardening plants trees kids school nature grow',desc:'Prune six trees, rebuild two beds, and make the harvest easier for students to share.'},
{id:'repair',title:'Sunday repair table',area:'Harbourview',type:'Skills',time:1,people:4,color:'blue',keywords:'fix fixing mend clothes electronics reuse recycle maker',desc:'Help neighbours mend lamps, patch clothes, and keep useful things out of landfill.'},
{id:'pantry',title:'Restock the little pantry',area:'West Commons',type:'Food',time:1,people:12,color:'coral',keywords:'donate donation hunger groceries supplies meals food bank',desc:'Coordinate a low-waste pantry refill with shelf-stable food and hygiene basics.'},
{id:'walk',title:'Map a safer night walk',area:'North End',type:'Community',time:2,people:6,color:'violet',keywords:'safety accessibility lights walking streets map neighborhood community',desc:'Walk the route together and log lighting, crossings, and accessibility gaps.'}];
const filters=['All','Outdoors','Skills','Food','Community'] as const;
const projectIds=new Set(projects.map(project=>project.id));
const isSavedFilter=(value:unknown):value is string=>typeof value==='string'&&filters.includes(value as typeof filters[number]);
const isSavedQuery=(value:unknown):value is string=>typeof value==='string'&&value.length<=300;
const isSavedPlan=(value:unknown):value is string[]=>Array.isArray(value)&&value.every(id=>typeof id==='string'&&projectIds.has(id));
export default function Home(){
 const[filter,setFilter]=usePersistentState('patchwork.filter.v1','All',isSavedFilter);
 const[query,setQuery]=usePersistentState('patchwork.query.v1','',isSavedQuery);
 const[selected,setSelected,planRestored]=usePersistentState<string[]>('patchwork.plan.v1',['orchard','repair'],isSavedPlan);
 const[toast,setToast]=useState('');
 const visible=useMemo(()=>{const terms=query.toLowerCase().trim().split(/\s+/).filter(Boolean);return projects.filter(p=>(filter==='All'||p.type===filter)&&(!terms.length||terms.some(term=>`${p.title} ${p.area} ${p.type} ${p.keywords} ${p.desc}`.toLowerCase().includes(term))))},[filter,query]);
 const webMCPTools=useMemo<WebMCPTool[]>(()=>[
  {name:'search_neighborhood_projects',description:'Find current neighbourhood projects by area, interest, or available time, and show the search in the shared interface.',inputSchema:{type:'object',properties:{query:{type:'string'},max_hours:{type:'number'}}},execute:async(input)=>{const text=typeof input.query==='string'?input.query:'';const max=typeof input.max_hours==='number'?input.max_hours:8;setQuery(text);const matches=projects.filter(p=>p.time<=max&&`${p.title} ${p.area} ${p.type} ${p.keywords} ${p.desc}`.toLowerCase().includes(text.toLowerCase()));setToast(`Agent found ${matches.length} project${matches.length===1?'':'s'} and shared the search.`);return{projects:matches,shared_ui_updated:true}}},
  {name:'build_action_plan',description:'Create a realistic action plan from selected neighbourhood projects, display it for human review, and save it on this device.',inputSchema:{type:'object',properties:{project_ids:{type:'array',items:{type:'string'}}},required:['project_ids']},execute:async(input)=>{const ids=Array.isArray(input.project_ids)?input.project_ids.filter((id):id is string=>typeof id==='string'):[];const plan=projects.filter(p=>ids.includes(p.id));setSelected(plan.map(p=>p.id));const hours=plan.reduce((s,p)=>s+p.time,0);setToast(`Agent shared and saved a ${hours}-hour plan with ${plan.length} project${plan.length===1?'':'s'}.`);return{plan,total_hours:hours,shared_ui_updated:true,persisted_on_device:true}}},
  {name:'pledge_support',description:'Draft a support pledge and show it for human review. Never submit or commit without explicit human confirmation.',inputSchema:{type:'object',properties:{project_id:{type:'string'},contribution:{type:'string'}},required:['project_id','contribution']},execute:async(input)=>{const projectId=typeof input.project_id==='string'?input.project_id:'';const contribution=typeof input.contribution==='string'?input.contribution:'';setToast('Agent prepared a pledge draft. Human confirmation is required; nothing was submitted.');return{status:'confirmation_required',draft:{project_id:projectId,contribution},shared_ui_updated:true}}}
 ],[]);
 useWebMCP(webMCPTools);
 const total=selected.reduce((s,id)=>s+(projects.find(p=>p.id===id)?.time||0),0);
 return <main><nav className="nav"><a className="brand" href="#top"><span>p</span>patchwork</a><div className="navlinks"><a href="#projects">Find a project</a><a href="#how">How it works</a></div><button className="agent-pill" onClick={()=>{setSelected(['orchard','pantry']);setToast('Agent plan ready — you’re still in control.')}}>⌁ Ask my agent</button></nav>
 <section className="hero" id="top"><div className="eyebrow"><i/> PEOPLE + AGENTS, ON COMMON GROUND</div><h1>Small actions.<br/><em>Shared momentum.</em></h1><p className="lede">Patchwork turns local needs into clear, doable plans. Explore with your own eyes—or let your agent find the right way to pitch in.</p><form className="search" onSubmit={e=>{e.preventDefault();document.querySelector('#projects')?.scrollIntoView({behavior:'smooth'});if(visible.length){setSelected(s=>s.includes(visible[0].id)?s:[...s,visible[0].id]);setToast(`${visible.length} match${visible.length===1?'':'es'} found. ${visible[0].title} was added to your plan.`)}else setToast('No exact match yet — try garden, repair, food, or safety.')}}><span>⌕</span><input aria-label="Search projects" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try “help in a garden” or “donate food”"/><button type="submit">Explore <b>→</b></button></form><div className="trust"><span>● Live neighbourhood needs</span><span>✓ You approve every commitment</span><span>⌁ Agent-ready via WebMCP</span></div><div className="orbit orbit-a">garden</div><div className="orbit orbit-b">repair</div><div className="orbit orbit-c">share</div></section>
 <section className="projects" id="projects"><div className="section-head"><div><p className="kicker">HAPPENING NEARBY</p><h2>{query?`${visible.length} local match${visible.length===1?'':'es'}`:'Find your patch.'}</h2></div><p>{query?`Suggestions for “${query}” — add any project to shape your plan.`:'Real needs, shaped by the people closest to them.'}</p></div><div className="filters">{filters.map(f=><button key={f} className={filter===f?'active':''} onClick={()=>setFilter(f)}>{f}</button>)}</div><div className="project-grid">{visible.map((p,i)=><article className={`card ${p.color}`} key={p.id}><div className="card-top"><span>{p.type}</span><button aria-label={`Add ${p.title}`} className={selected.includes(p.id)?'picked':''} onClick={()=>setSelected(s=>s.includes(p.id)?s.filter(x=>x!==p.id):[...s,p.id])}>{selected.includes(p.id)?'✓':'+'}</button></div><div className="mini-art" aria-hidden="true"><i/><i/><i/></div><p className="place">{p.area} · {p.time} hr{p.time>1?'s':''}</p><h3>{p.title}</h3><p>{p.desc}</p><footer><span>{p.people} neighbours in</span><b>{String(i+1).padStart(2,'0')}</b></footer></article>)}{visible.length===0&&<div className="empty"><span>⌁</span><h3>No exact match—yet.</h3><p>Try a broader idea like garden, repair, food, safety, or community.</p><button onClick={()=>{setQuery('');setFilter('All')}}>Show every project</button></div>}</div></section>
 <section className="plan" id="how"><div className="plan-copy"><p className="kicker">YOUR SHARED PLAN</p><h2>Keep the human<br/>in the loop.</h2><p>Your agent can discover, compare, and organize. Only you can make the commitment.</p><div className="steps"><span><b>1</b> Tell your agent what matters</span><span><b>2</b> Review a grounded local plan</span><span><b>3</b> Approve what you’ll contribute</span></div></div><div className="plan-card"><div className="plan-title"><div><small>WEEKEND PLAN</small><strong>{selected.length} good ways to help</strong></div><span>{total}h total</span></div>{projects.filter(p=>selected.includes(p.id)).map(p=><div className="plan-row" key={p.id}><i className={p.color}/><div><b>{p.title}</b><small>{p.area} · {p.time} hr</small></div><button aria-label={`Remove ${p.title}`} onClick={()=>setSelected(s=>s.filter(x=>x!==p.id))}>×</button></div>)}<div className="plan-actions"><button className="clear-plan" onClick={()=>{setSelected([]);setToast('Saved plan cleared on this device.')}} disabled={!selected.length}>Clear plan</button><span>{planRestored?'Saved on this device':'Restoring plan…'}</span></div><button className="review" onClick={()=>setToast(`Plan reviewed: ${selected.length} projects, ${total} hours. No pledge sent.`)}>Review my plan →</button><p className="safe">Nothing is submitted without your confirmation.</p></div></section>
 <footer className="footer"><a className="brand" href="#top"><span>p</span>patchwork</a><p>The open web, made actionable together.</p><span>Built with WebMCP</span></footer>{toast&&<button className="toast" onClick={()=>setToast('')}>{toast}<span>×</span></button>}</main>}
