'use client';
import { useEffect, useMemo, useState } from 'react';
const projects=[
{id:'orchard',title:'Revive the schoolyard orchard',area:'North End',type:'Outdoors',time:2,people:8,color:'lime',desc:'Prune six trees, rebuild two beds, and make the harvest easier for students to share.'},
{id:'repair',title:'Sunday repair table',area:'Harbourview',type:'Skills',time:1,people:4,color:'blue',desc:'Help neighbours mend lamps, patch clothes, and keep useful things out of landfill.'},
{id:'pantry',title:'Restock the little pantry',area:'West Commons',type:'Food',time:1,people:12,color:'coral',desc:'Coordinate a low-waste pantry refill with shelf-stable food and hygiene basics.'},
{id:'walk',title:'Map a safer night walk',area:'North End',type:'Community',time:2,people:6,color:'violet',desc:'Walk the route together and log lighting, crossings, and accessibility gaps.'}];
declare global{interface Document{modelContext?:{registerTool:(tool:unknown)=>void}}}
export default function Home(){
 const[filter,setFilter]=useState('All'),[query,setQuery]=useState(''),[selected,setSelected]=useState<string[]>(['orchard','repair']),[toast,setToast]=useState('');
 const visible=useMemo(()=>projects.filter(p=>(filter==='All'||p.type===filter)&&`${p.title} ${p.area} ${p.desc}`.toLowerCase().includes(query.toLowerCase())),[filter,query]);
 useEffect(()=>{if(!document.modelContext)return;
 document.modelContext.registerTool({name:'search_neighborhood_projects',description:'Find current neighbourhood projects by area, interest, or available time.',inputSchema:{type:'object',properties:{query:{type:'string'},max_hours:{type:'number'}}},execute:async({query='',max_hours=8}:{query?:string;max_hours?:number})=>({projects:projects.filter(p=>p.time<=max_hours&&`${p.title} ${p.area} ${p.type} ${p.desc}`.toLowerCase().includes(query.toLowerCase()))})});
 document.modelContext.registerTool({name:'build_action_plan',description:'Create a realistic action plan from selected neighbourhood projects.',inputSchema:{type:'object',properties:{project_ids:{type:'array',items:{type:'string'}}},required:['project_ids']},execute:async({project_ids}:{project_ids:string[]})=>({plan:projects.filter(p=>project_ids.includes(p.id)),total_hours:projects.filter(p=>project_ids.includes(p.id)).reduce((s,p)=>s+p.time,0)})});
 document.modelContext.registerTool({name:'pledge_support',description:'Draft a support pledge for a project. Always ask the human to confirm before submitting.',inputSchema:{type:'object',properties:{project_id:{type:'string'},contribution:{type:'string'}},required:['project_id','contribution']},execute:async(input:{project_id:string;contribution:string})=>({status:'confirmation_required',draft:input})});},[]);
 const total=selected.reduce((s,id)=>s+(projects.find(p=>p.id===id)?.time||0),0);
 return <main><nav className="nav"><a className="brand" href="#top"><span>p</span>patchwork</a><div className="navlinks"><a href="#projects">Find a project</a><a href="#how">How it works</a></div><button className="agent-pill" onClick={()=>{setSelected(['orchard','pantry']);setToast('Agent plan ready — you’re still in control.')}}>⌁ Ask my agent</button></nav>
 <section className="hero" id="top"><div className="eyebrow"><i/> PEOPLE + AGENTS, ON COMMON GROUND</div><h1>Small actions.<br/><em>Shared momentum.</em></h1><p className="lede">Patchwork turns local needs into clear, doable plans. Explore with your own eyes—or let your agent find the right way to pitch in.</p><div className="search"><span>⌕</span><input aria-label="Search projects" value={query} onChange={e=>setQuery(e.target.value)} placeholder="What would you like to help with?"/><button onClick={()=>document.querySelector('#projects')?.scrollIntoView({behavior:'smooth'})}>Explore <b>→</b></button></div><div className="trust"><span>● Live neighbourhood needs</span><span>✓ You approve every commitment</span><span>⌁ Agent-ready via WebMCP</span></div><div className="orbit orbit-a">garden</div><div className="orbit orbit-b">repair</div><div className="orbit orbit-c">share</div></section>
 <section className="projects" id="projects"><div className="section-head"><div><p className="kicker">HAPPENING NEARBY</p><h2>Find your patch.</h2></div><p>Real needs, shaped by the people closest to them.</p></div><div className="filters">{['All','Outdoors','Skills','Food','Community'].map(f=><button key={f} className={filter===f?'active':''} onClick={()=>setFilter(f)}>{f}</button>)}</div><div className="project-grid">{visible.map((p,i)=><article className={`card ${p.color}`} key={p.id}><div className="card-top"><span>{p.type}</span><button aria-label={`Add ${p.title}`} className={selected.includes(p.id)?'picked':''} onClick={()=>setSelected(s=>s.includes(p.id)?s.filter(x=>x!==p.id):[...s,p.id])}>{selected.includes(p.id)?'✓':'+'}</button></div><div className="mini-art" aria-hidden="true"><i/><i/><i/></div><p className="place">{p.area} · {p.time} hr{p.time>1?'s':''}</p><h3>{p.title}</h3><p>{p.desc}</p><footer><span>{p.people} neighbours in</span><b>{String(i+1).padStart(2,'0')}</b></footer></article>)}</div></section>
 <section className="plan" id="how"><div className="plan-copy"><p className="kicker">YOUR SHARED PLAN</p><h2>Keep the human<br/>in the loop.</h2><p>Your agent can discover, compare, and organize. Only you can make the commitment.</p><div className="steps"><span><b>1</b> Tell your agent what matters</span><span><b>2</b> Review a grounded local plan</span><span><b>3</b> Approve what you’ll contribute</span></div></div><div className="plan-card"><div className="plan-title"><div><small>WEEKEND PLAN</small><strong>{selected.length} good ways to help</strong></div><span>{total}h total</span></div>{projects.filter(p=>selected.includes(p.id)).map(p=><div className="plan-row" key={p.id}><i className={p.color}/><div><b>{p.title}</b><small>{p.area} · {p.time} hr</small></div><button onClick={()=>setSelected(s=>s.filter(x=>x!==p.id))}>×</button></div>)}<button className="review" onClick={()=>setToast(`Plan reviewed: ${selected.length} projects, ${total} hours. No pledge sent.`)}>Review my plan →</button><p className="safe">Nothing is submitted without your confirmation.</p></div></section>
 <footer className="footer"><a className="brand" href="#top"><span>p</span>patchwork</a><p>The open web, made actionable together.</p><span>Built with WebMCP</span></footer>{toast&&<button className="toast" onClick={()=>setToast('')}>{toast}<span>×</span></button>}</main>}
